### PR TITLE
models: Add last_measurements to device

### PR DESCRIPTION
**Pull request by Raphexion**
Add last_measurements to device.

### CODE REVIEW

**Comment by Raphexion** [comment]
@skovmand If you have time, could you help me test this, I am a little unsure how to do it.

**Comment by skovmand** [comment]
I think it looks correct. The foreign_key is on `Measurement` and the a `Device` can have many measurements :+1:

Sometimes it's a good sanity check to use it in a project before merging the PR to make sure everything needed is included (e.g. endpoints, behaviours, etc.). You can do that by changing `mix.exs` to use `wise_homex` from a path instead of fetching it from the GitHub repo.

Is there an issue that this is related to in our other projects?

**Comment by Raphexion** [comment]
I have verified it with Arwen and it seems to work as expected.

**Review by skovmand — APPROVED** [review]
:+1:

**Pull request merged**
